Complete refactoring of the daemon's Unix permissions: now it does not need to run as root anymore, and the toggle_suid function has been disabled. An independent script using inotify (afdsiperm.sh) stays active in background to properly fix permissions of datasets: this the only part that must be run as root.

diff --git a/etc/init.d/afdsmgrd.in b/etc/init.d/afdsmgrd.in
--- a/etc/init.d/afdsmgrd.in
+++ b/etc/init.d/afdsmgrd.in
@@ -81,24 +81,6 @@ export PROG="$AFDSMGRD_PROG"
 # Basename of program
 export BASEPROG=`basename "$PROG"`
 
-# File that holds the PID
-export PIDFILE="$AFDSMGRD_PIDFILE"
-
-# Log file
-export LOGFILE="$AFDSMGRD_LOGFILE"
-
-# Log dir
-export LOGDIR="$AFDSMGRD_LOGDIR"
-
-# Configuration file
-export CONF="$AFDSMGRD_CONF"
-
-# Daemon user
-export SUSER="$AFDSMGRD_USER"
-
-# Log level
-export LOG_LEVEL="$AFDSMGRD_LOGLEVEL"
-
 # Grace time before "kill -9", in seconds
 export GRACEKILL_SEC=20
 
@@ -132,7 +114,7 @@ function MsgEnd() {
 
 # Echoes the PID of the program if running; empty string otherwise
 function GetPid() {
-  local PID=`cat "$PIDFILE" 2> /dev/null`
+  local PID=`cat "$AFDSMGRD_PIDFILE" 2> /dev/null`
   kill -0 "$PID" 2> /dev/null && echo $PID
 }
 
@@ -152,8 +134,8 @@ function StopKill() {
 }
 
 # Cleanup of daemon's temporary directory: called on startup and shutdown. This
-# is the first function to customize. This function cleans *every* afdsmgrd temp
-# directory associated to an instance that is no longer running
+# function cleans *every* afdsmgrd temp directory associated to an instance that
+# is no longer running
 function Cleanup() {
 
   local Pid
@@ -180,26 +162,90 @@ function LaunchDaemon() {
   Cleanup
 
   # Change permissions of log directory
-  mkdir -p "$LOGDIR" > /dev/null 2>&1
-  touch "$LOGFILE" > /dev/null 2>&1
-  chmod -R u=rwX,g=rX,o=rX "$LOGDIR" > /dev/null 2>&1
-  chown -R "$SUSER" "$LOGDIR" > /dev/null 2>&1
+  mkdir -p "$AFDSMGRD_LOGDIR" > /dev/null 2>&1
+  touch "$AFDSMGRD_LOGFILE" > /dev/null 2>&1
+  chmod -R u=rwX,g=rX,o=rX "$AFDSMGRD_LOGDIR" > /dev/null 2>&1
+  chown -R "$AFDSMGRD_USER:$AFDSMGRD_GROUP" "$AFDSMGRD_LOGDIR" > /dev/null 2>&1
 
   # Creates directory for pidfile (if not exists)
-  mkdir -p $(dirname "$PIDFILE")
+  mkdir -p $(dirname "$AFDSMGRD_PIDFILE")
 
-  # This is a setuid program: for security reasons, LD_LIBRARY_PATH is not
-  # inherited in the environment inside the daemon
-  ( export LD_LIBRARY_PATH="$ROOTSYS/lib:$AFDSMGRD_LIBS:$LD_LIBRARY_PATH" ; \
-    "$AFDSMGRD_PROG" -b -u "$SUSER" -p "$PIDFILE" -c "$CONF" -d "$LOG_LEVEL" \
-    -l "$LOGFILE" -e "$AFDSMGRD_LIBEXEC" )
+  # LD_LIBRARY_PATH is not inherited in the environment inside the daemon
+  local Tmp=`mktemp /tmp/start-afdsmgrd-XXXXX`
+  cat > $Tmp <<EOF
+#!/bin/sh
+export LD_LIBRARY_PATH="$ROOTSYS/lib:$AFDSMGRD_LIBS:$LD_LIBRARY_PATH"
+"$AFDSMGRD_PROG" -b -p "$AFDSMGRD_PIDFILE" -c "$AFDSMGRD_CONF" \\
+  -d "$AFDSMGRD_LOGLEVEL" \\
+  -l "$AFDSMGRD_LOGFILE" -e "$AFDSMGRD_LIBEXEC"
+EOF
 
-  return $?
+  local RetVal Whoami DsPath
+  Whoami=`whoami`
+
+  chmod 0700 $Tmp
+
+  if [ "$Whoami" == "$AFDSMGRD_USER" ]; then
+    # We are the daemon's user
+    $Tmp
+    RetVal=$?
+  elif [ "$Whoami" == 'root' ]; then
+    # We are root: daemon starts and stays unprivileged
+    chown $AFDSMGRD_USER $Tmp
+    su $AFDSMGRD_USER -c $Tmp
+    RetVal=$?
+  else
+    # User not eligible to run daemon!
+    RetVal=1
+  fi
+
+  rm -f $Tmp
+
+  return $RetVal
+}
+
+# Start/stop permission fixer
+function DsPerm() {
+
+  local DsPath RetVal Action
+  Action="$1"
+
+  if [ "$Action" == 'start' ]; then
+    MsgBegin 'Starting afdsiperm'
+    DsPath=`cat "$AFDSMGRD_CONF" | grep -v '^[ \t]*#' | \
+      grep 'xpd.datasetsrc' | \
+      perl -ne '/[ \t]url:([^ \t]*)/ and print "$1\n"'`
+    if [ "$DsPath" == '' ]; then
+      MsgEnd 1 'cannot find dataset path'
+      return 1
+    fi
+
+    ( cd /tmp ; \
+      nohup "$AFDSMGRD_LIBEXEC"/afdsiperm.sh \
+        "$DsPath" "$AFDSMGRD_USER" > /dev/null 2>&1 & )
+
+    # Are we running?
+    sleep 1
+    pgrep afdsiperm.sh > /dev/null
+    RetVal=$?
+
+    MsgEnd $RetVal
+    return $RetVal
+  elif [ "$Action" == 'stop' ]; then
+    MsgBegin 'Stopping afdsiperm'
+    "$AFDSMGRD_LIBEXEC"/afdsiperm.sh --kill > /dev/null 2>&1
+    MsgEnd $?
+  fi
+
 }
 
 # Starts the daemon (if not running)
 function Start() {
   local PID RETVAL
+
+  # Failure in afdsiperm does not inhibit afdsmgrd (for now)
+  [ `whoami` == 'root' ] && DsPerm start
+
   MsgBegin "Starting $BASEPROG"
   PID=`GetPid`
   if [ "$PID" == "" ]; then
@@ -211,12 +257,13 @@ function Start() {
     RETVAL=1
   fi
   return $RETVAL
+
 }
 
 # Stops the daemon
 function Stop() {
   local PID RETVAL
-  MsgBegin "Stopping $BASEPROG (waiting max ${GRACEKILL_SEC}s)..."
+  MsgBegin "Stopping $BASEPROG (waiting max ${GRACEKILL_SEC}s)"
   PID=`GetPid`
   if [ "$PID" == "" ]; then
     MsgEnd 0 "not running"
@@ -225,23 +272,27 @@ function Stop() {
     StopKill $PID
     RETVAL=$?
     if [ $RETVAL == 0 ]; then
-      rm -f "$PIDFILE"
+      rm -f "$AFDSMGRD_PIDFILE"
       Cleanup
     fi
     MsgEnd $RETVAL
   fi
+
+  [ `whoami` == 'root' ] && DsPerm stop
+
   return $RETVAL
 }
 
 # Status of the daemon; returns 0 if running, nonzero otherwise
 function Status() {
-  local PID
-  PID=`GetPid`
-  if [ "$PID" == "" ]; then
+  local Pid NFiles
+  Pid=`GetPid`
+  if [ "$Pid" == "" ]; then
     Msg "$BASEPROG is not running"
     return 1
   else
-    Msg "$BASEPROG is running with PID=$PID"
+    NFiles=`lsof -p $Pid 2> /dev/null | grep -c $Pid`
+    Msg "$BASEPROG is running with PID $Pid ($NFiles files open)"
     return 0
   fi
 }
@@ -250,8 +301,8 @@ function Status() {
 function ShowLog() {
   Status
   if [ $? == 0 ]; then
-    echo "Showing last lines of $LOGFILE with tail -f (abort with Ctrl+C):"
-    tail -f "$LOGFILE"
+    echo "Showing last lines of $AFDSMGRD_LOGFILE (abort with Ctrl+C):"
+    tail -f "$AFDSMGRD_LOGFILE"
   fi
 }
 
@@ -284,11 +335,20 @@ case "$1" in
     echo "Using startup configuration file: $CF"
     exit 0
   ;;
+  dsiperm-start)
+    DsPerm start
+    exit $?
+  ;;
+  dsiperm-stop)
+    DsPerm stop
+    exit $?
+  ;;
   #drain)
   # to be implemented
   #;;
   *)
-    echo  "Usage: `basename $0` {start|stop|restart|condrestart|reload|status|sysconfig|log}"
+    echo  "Usage: `basename $0`" \
+      "{start|stop|restart|condrestart|dsiperm-start|dsiperm-stop|reload|status|sysconfig|log}"
     exit 1
   ;;
 esac
