* In devel branch: added a "dollar substitution" in af::regex facility, which enables variable substitution in staging command line composition (implemented) and variables substitution in af::config (next to come)

diff --git a/branches/devel/etc/init.d/afdsmgrd.in b/branches/devel/etc/init.d/afdsmgrd.in
--- a/branches/devel/etc/init.d/afdsmgrd.in
+++ b/branches/devel/etc/init.d/afdsmgrd.in
@@ -92,6 +92,9 @@ export SUSER="$AFDSMGRD_USER"
 # Log level
 export LOG_LEVEL="$AFDSMGRD_LOGLEVEL"
 
+# Temporary directory (hardcoded)
+export TEMPDIR="/tmp/afdsmgrd"
+
 #
 # Functions
 #
@@ -138,9 +141,22 @@ function StopKill() {
   kill -0 "$PID" 2> /dev/null && return 1 || return 0
 }
 
-# This is most likely the only function to edit: it contains the custom
-# commands to effectively launch the daemon
+# Cleanup of daemon's temporary directory: called on startup and shutdown. This
+# is the first function to customize
+function Cleanup() {
+  rm -rf "$TEMPDIR"
+  return $?
+}
+
+# This is the second function to edit: it contains the custom commands to
+# effectively launch the daemon
 function LaunchDaemon() {
+
+  # Creates temporary directory
+  Cleanup
+  mkdir -p "$TEMPDIR"
+  chmod -R u=rwX,g=rX,o=rX "$TEMPDIR" > /dev/null 2>&1
+  chown -R "$SUSER" "$TEMPDIR" > /dev/null 2>&1
 
   # Change permissions of log directory
   mkdir -p "$LOGDIR" > /dev/null 2>&1
@@ -182,7 +198,10 @@ function Stop() {
   else
     StopKill $PID
     RETVAL=$?
-    [ $RETVAL == 0 ] && rm -f "$PIDFILE"
+    if [ $RETVAL == 0 ]; then
+      rm -f "$PIDFILE"
+      Cleanup
+    fi
     MsgEnd $RETVAL
   fi
   return $RETVAL
