* Big commit!  * ROOT macros have better names  * External command facility now has better granularity over grace time (do not check every second, but every fraction of a second)  * The last point was to implement a missing feature (and memory leak): elements in command queue are now deleted when invoking exit, both in daemon and verifier. The dtor causes kill (-HUP, -KILL) to be called automatically. Timeout between -HUP and -KILL with a granularity of 1 sec caused the daemon to take very long before stopping.  * ROOT process now takes the PID of the calling BASH process through "exec"  * Changed CMakeLists: a macro has been added to configure files  * Now, xrdstagetool is called inside a script (much lighter), and a ROOT session is invoked only when verifying the file and the file has already been downloaded

diff --git a/scripts/afdsmgrd-xrd-stage-verify.sh.in b/scripts/afdsmgrd-xrd-stage-verify.sh.in
--- a/scripts/afdsmgrd-xrd-stage-verify.sh.in
+++ b/scripts/afdsmgrd-xrd-stage-verify.sh.in
@@ -1,13 +1,16 @@
 #!/bin/bash
 
 #
-# afdsmgrd-root.sh -- by Dario Berzano <dario.berzano@cern.ch>
+# afdsmgrd-xrd-stage-verify.sh -- by Dario Berzano <dario.berzano@cern.ch>
 #
 # This file is part of afdsmgrd -- see http://code.google.com/p/afdsmgrd
 #
 # This script uses the same environment variables defined in sysconfig file of
 # afdsmgrd to set the environment for ROOT and launch it with the given
 # parameters.
+#
+# First of all, file is downloaded by means of the xrdstagetool utility. If the
+# download succeeds, ROOT is called with a proper macro to check file's integrity
 #
 # It has been created to overcome a "problem" with setuid programs like
 # afdsmgrd: in these programs, LD_LIBRARY_PATH is unset right after changing
@@ -37,5 +40,29 @@ export ROOTSYS="@ROOTSYS@"
 export LD_LIBRARY_PATH="$AFDSMGRD_EXTCMD_LIBS:$ROOTSYS/lib:$LD_LIBRARY_PATH"
 export PATH="$ROOTSYS/bin:$AFDSMGRD_EXTCMD_PATH:$PATH"
 
-# Replace current shell with ROOT
-exec root.exe "$@"
+# Arguments: first one is the url to stage, second is the tree name (opt.)
+export URL="$1"
+export TREE="$2"
+
+# Split URL into host:port, filename and anchor; note that queries (?...) aren't
+# supported!
+if [[ "$URL" =~ ^root://([^/]+)/([^\#\?]+)(.*)?$ ]]; then
+  HOSTPORT=${BASH_REMATCH[1]}
+  FILENAME=${BASH_REMATCH[2]}
+  REMAIN=${BASH_REMATCH[3]}
+  CLEANURL="root://$HOSTPORT/$FILENAME"
+else
+  echo "FAIL $URL Reason: cant_parse_url"
+  exit 0
+fi
+
+# Call xrdstagetool
+xrdstagetool -d 0 $CLEANURL | grep '^OK[ \t]' > /dev/null 2>&1
+
+if [ $? == 0 ]; then
+  # Status is OK: verify the file
+  exec root.exe -b -q "@DIR_LIBEXEC@"/afdsmgrd-macros/Verify.C'("'$URL'", "'$TREE'")'
+fi
+
+# Here, status is failed: report it
+echo "FAIL $CLEANURL"
