Massive commit for v0.9.3, to be included in ROOT v5.30.
(Some other commits may follow to fix last-minute glitches.)

afverifier:

 - Added a command-line option to launch removal on (trusted) corrupted bit (-x)
 - Added in configuration file the proper option for remove command (verifier.erasecmd)
 - Added the proper default script for xrootd removal
 - Added a command-line option to merge all the processed datasets into a single big dataset named /merged/merged/merged (-m option) - Added a command line option (-w) to filter input entries in the usual form SsCc: for instance, using "-x -w C" only corrupted files are processed, and they are removed in parallel                           
 - In xrootd locate script: fixed wrong shell redirection order
 - Also fixed a "default parameter" bug in LocateVerifyXrd.C macro

afdsmgrd:

 - Print a "goodbye" message when gracefully quitting in log facility

AFDSUtil:

 - In afRepairDs(): added an option to remove the endpoint URL (namely "delendpurl") from the corrupted files (all URLs but last two -- redirector and originating URL -- are removed)
 - In CreateDataSetFromAliEn: added an "update" option to add new entries to existing datasets -- useful if files are added to an existing production or real data
 - Added the (currently unused) creation of a temporary dataset repository

af::opQueue class:

 - Added a 16-bit freely usable "flags" variable to queue entries and database

af::dataSetList class:

 - Saving datasets now works with newly added TFileCollections: no longer needed for a dataset to be already in the list to save it back

diff --git a/scripts/afverifier-xrd-rm.sh.in b/scripts/afverifier-xrd-rm.sh.in
--- a/scripts/afverifier-xrd-rm.sh.in
+++ b/scripts/afverifier-xrd-rm.sh.in
@@ -1,11 +1,12 @@
 #!/bin/bash
 
 #
-# afverify-xrd-locate.sh -- by Dario Berzano <dario.berzano@cern.ch>
+# afverify-xrd-rm.sh -- by Dario Berzano <dario.berzano@cern.ch>
 #
 # This file is part of afdsmgrd -- see http://code.google.com/p/afdsmgrd
 #
-# Wrapper around xrd locateall command, see macros/Verify.C for info on output.
+# Wrapper around xrd rm command. Outputs OK on success, FAIL if for some reason
+# the command can not be launched or terminated abruptly.
 #
 
 # Get the configuration variables from the first configuration file found
@@ -52,35 +53,29 @@ else
 fi
 
 # Launch xrd
-export TMPOUT=$(mktemp /tmp/.afverifier-xrd-locate-XXXXX)
-xrd $HOSTPORT locateall $FILENAME > $TMPOUT 2>&1
-#echo $?
+export TMPOUT=$(mktemp /tmp/.afverifier-xrd-rm-XXXXX)
+xrd $HOSTPORT rm $FILENAME > $TMPOUT 2>&1
+export CODE=$?
+export XRDCODE
 
-if [ $? != 0 ]; then
-  rm $TMPOUT
-  echo "FAIL $CLEANURL Reason: xrd_error"
-  exit 0
-fi
+# Uncomment for debug
+#cat $TMPOUT
 
-# Get Location: line
-export LOCATION=$(cat $TMPOUT | grep "Location: " | head -n1)
-
-# Parse location server
-export ENDP_URL
-if [[ $LOCATION =~ Location:\\s\'(.*)\' ]]; then
-  ENDP_URL="root://${BASH_REMATCH[1]}/${FILENAME}${REMAIN}"
-  echo "OK $CLEANURL EndpointUrl: $ENDP_URL"
-else
-
-  # File is not staged (empirically... bad xrd, bad...)
-  cat $TMPOUT | grep 'matching files' > /dev/null 2>&1
-  if [ $? == 0 ]; then
-    echo "FAIL $CLEANURL Reason: not_staged"
+if [ $CODE == 0 ]; then
+  XRDCODE=$(grep '^Error ' $TMPOUT 2>&1 | \
+    perl -ne '/^Error\s+([0-9]+)/; print "$1\n"')
+  if [ "$XRDCODE" != "" ]; then
+    echo "FAIL $CLEANURL Reason: xrd_err_$XRDCODE"
   else
-    # No reason given, generic error (server down, etc.)
-    echo "FAIL $CLEANURL"
+    grep 'to any server' $TMPOUT > /dev/null 2>&1
+    if [ $? == 0 ]; then
+      echo "FAIL $CLEANURL Reason: server_down"
+    else
+      echo "OK $CLEANURL"
+    fi
   fi
-
+else
+  echo "FAIL $CLEANURL Reason: exit_code_$CODE"
 fi
 
 rm $TMPOUT
